# Generated by Django 5.1 on 2024-08-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
